import pandas as pd
from lxml import etree


def extract_xml_fields(element):
    """Yields (name, value) data points recursively through a TCX or GPX XML element"""

    for el in element.iter():
        # Some (name, value) pairs are stored as XML attributes
        for key, value in el.attrib.items():
            localname = etree.QName(key).localname
            if localname != 'type':
                yield (localname, value)

        # In a TCX file, some values are buried one level down in a 'Value' element
        if el.text is None or el.text.isspace():
            child = next(el.iterchildren())
            parent_localname = etree.QName(el).localname
            child_localname = etree.QName(child).localname
            if child_localname == 'Value':
                yield (parent_localname, child.text)

        # But most values are recorded as leaf element text
        else:
            localname = etree.QName(el).localname
            if localname != 'Value':
                yield (localname, el.text)


def cleanup_xml_dataframe(df, time_col):
    """Common post-processing for DataFrames extracted from a TCX or GPX XML element"""

    df = df.convert_dtypes().astype(float, errors='ignore')
    df[time_col] = pd.to_datetime(df[time_col])

    # Conversion from meters and m/s to km and kph is done to align with processing done
    # by fitdecode.StandardUnitsDataProcessor. Note these column names apply to TCX files
    # only; GPX files don't seem to have distance and speed information.
    for col in df.columns:
        if 'Distance' in col:
            df[col] = df[col] / 1000.0
            df = df.rename(columns={col: col.replace('Meters', 'Km')})
        if 'Speed' in col:
            df[col] = df[col] * 60.0 * 60.0 / 1000.0

    return df


def parse_tcx(file):
    """Loads a TCX activity into Pandas DataFrames

    Assumes that the TCX file is all one activity. Files with multiple activities will be
    merged into one set of return values, possibly over-writing some fields.

    Arguments:
        file: File-like or path-like object. A path-like argument ending in .gz will be
              transparently unzipped before processing.

    Returns:
        A tuple of (points, laps, extra)

        points: Time-indexed DataFrame of sensor data recorded during activity
        laps: DataFrame of lap information from the activity
        extra: Dict of selected additional information from the activity
    """

    # lxml takes care of identifying and handling a gzipped file
    parser = etree.XMLParser(recover=True)
    root = etree.parse(file, parser).getroot()

    # TCX files occasionally have duplicate timestamps, just drop those
    points = pd.DataFrame(dict(extract_xml_fields(element))
                          for element in root.iter('{*}Trackpoint'))
    points = cleanup_xml_dataframe(points, 'Time').set_index('Time')
    points = points[~points.index.duplicated()]

    # This drops all Trackpoints from the XML data so they don't show up in lap data
    for element in root.iterfind('.//{*}Track'):
        element.getparent().remove(element)

    laps = pd.DataFrame(dict(extract_xml_fields(element))
                        for element in root.iter('{*}Lap'))
    laps = cleanup_xml_dataframe(laps, 'StartTime')

    extra = dict()
    for element in root.iter('{*}Creator'):
        extra.update(dict(extract_xml_fields(element)))

    return points, laps, extra


def parse_gpx(file):
    """Loads a GPX activity into a Pandas DataFrame

    Assumes that the GPX file is all one activity. Files with multiple tracks will be
    merged into one set of return values, possibly over-writing some fields.

    Arguments:
        file: File-like or path-like object. A path-like argument ending in .gz will be
              transparently unzipped before processing.

    Returns:
        A tuple of (points, laps, extra)

        points: Time-indexed DataFrame of sensor data recorded during activity
        laps: An empty Pandas DataFrame provided for compatibility with other parsers
        extra: Dict of additional information from the activity
    """

    # Note there is a 'gpxpy' library that provides comprehensive handling of GPX files.
    # For GPX files generated by Strava and Garmin Connect it works well enough to suck
    # the data straight out of the XML like we do above for TCX files.

    parser = etree.XMLParser(recover=True)
    root = etree.parse(file, parser).getroot()

    points = pd.DataFrame(dict(extract_xml_fields(element))
                          for element in root.iter('{*}trkpt'))
    points = cleanup_xml_dataframe(points, 'time').set_index('time')
    points = points[~points.index.duplicated()]

    for element in root.iterfind('.//{*}trkseg'):
        element.getparent().remove(element)

    extra = dict()
    for element in root.iter():
        extra.update(dict(extract_xml_fields(element)))
    extra.pop('schemaLocation', None)

    return points, pd.DataFrame(), extra
